# Generated by Django 6.0.2 on 2026-02-07 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('pk', models.CompositePrimaryKey('course_id', 'content_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('pk', models.CompositePrimaryKey('course_id', 'instructor_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTextbook',
            fields=[
                ('pk', models.CompositePrimaryKey('course_id', 'isbn_number', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_textbook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('pk', models.CompositePrimaryKey('course_id', 'topic_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseUniversity',
            fields=[
                ('pk', models.CompositePrimaryKey('course_id', 'university_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('pk', models.CompositePrimaryKey('student_id', 'course_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'enrollment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('expertise', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlineContent',
            fields=[
                ('content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'online_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('isbn_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'textbook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.IntegerField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('instructor_id', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Instructor', 'Instructor'), ('Student', 'Student'), ('Analyst', 'Analyst')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
